# Generated by Django 6.0 on 2026-05-16 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_from', models.CharField(max_length=50)),
                ('reaches_to', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('reach_time', models.DateTimeField()),
                ('buisiness_class_price', models.PositiveIntegerField()),
                ('non_business_class_price', models.PositiveIntegerField()),
                ('no_of_business_class_seets', models.PositiveIntegerField()),
                ('no_of_non_business_class_seets', models.PositiveIntegerField()),
                ('features', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=50)),
                ('is_booked', models.BooleanField(default=False)),
                ('features', models.TextField()),
                ('is_business_seat', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.flight')),
                ('business_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.seat')),
            ],
        ),
    ]
