# Generated by Django 6.0 on 2026-05-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='features',
            field=models.TextField(null=True),
        ),
    ]
