# Generated by Django 6.0 on 2026-05-18 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_alter_seat_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='travelapp.flight'),
        ),
    ]
