# Generated by Django 6.0 on 2026-05-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_alter_seat_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='kilometers',
            field=models.CharField(default=5000, max_length=50),
            preserve_default=False,
        ),
    ]
