# Generated by Django 6.0.5 on 2026-05-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_flight_kilometers'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='image',
            field=models.ImageField(default='kdkjkd', upload_to='images'),
            preserve_default=False,
        ),
    ]
